name: Banana Classification CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check app syntax
      run: |
        python -m py_compile app.py
        
    - name: Check model training script
      run: |
        python -m py_compile model/train_model.py
        
    - name: Test basic import
      run: |
        python -c "import app; print('App imports successfully')"